NAMESPACE: 'default'
K8S_REPLICAS: '1'
K8S_MAX_UNAVAIL: '1'
K8S_MAX_SURGE: '1'
AUTOSCALE_MIN_REPLICA: '1'
AUTOSCALE_MAX_REPLICA: '2'
AUTOSCALE_CPU_PERCENTAGE: '50'
SECRET: 'mysecret'
TOLERATIONS: 'red'
NODENAME: 'worker2' 
SERVICENAME: 'user-service'
DOCKER_APP_IMAGE: 'shubhamdevops2/user:0.0.24-2022-08-27-16-48-21-main'

mongo:
  docker_image: 'mongo'
  name: 'mongo'
  location: '/app/*'
  port: 27017
  k8s_req:
    memory: '150Mi'
    cpu: '100m'
    storage: '1Gi'
  k8s_limit:
    memory: '250Mi'
    cpu: '200m'
    storage: '2Gi'

user:
  name: 'user'
  location: '/app/*'
  port: 8081
  k8s_req_mem: '500Mi'

  
  
